// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxgypuddfltlqqjqqnqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4Z3lwdWRkZmx0bHFxanFxbnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODU2NjYsImV4cCI6MjA2NTY2MTY2Nn0.CqYogArAVYrirtmcPPhaBUUknK2qotPEdYeowvlfvpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
